name: Banking System Configuration Check

on: [push]

jobs:
  banking-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Make Scripts Executable
        run: |
          chmod +x transaction.sh monitor_transactions.sh create_account.sh

      # Test 1: Transaction Logging
      - name: Test Transaction Logging
        run: |
          ./transaction.sh 12345 deposit 5000
          ./transaction.sh 67890 withdraw 60000

          # Check if transactions are logged correctly
          grep "Account: 12345 | Deposit: 5000" transaction_log.txt || (echo "Deposit transaction logging failed!" && exit 1)
          grep "Account: 67890 | Withdraw: 60000" transaction_log.txt || (echo "Withdraw transaction logging failed!" && exit 1)

          # Check for high-value transaction warning
          output=$(./transaction.sh 67890 withdraw 60000)
          echo "$output" | grep "ALERT: High-value transaction detected!" || (echo "High-value withdrawal alert failed!" && exit 1)

      # Test 2: Monitoring Suspicious Transactions
      - name: Test Monitoring Suspicious Transactions
        run: |
          # Run the monitoring script and capture output
          ./monitor_transactions.sh > monitor_output.txt

          # Check if the output includes the suspicious transaction
          grep "Withdraw: 60000" monitor_output.txt || (echo "Monitoring script failed to detect suspicious transaction!" && exit 1)

      # Test 3: Account Creation
      - name: Test Account Creation
        run: |
          ./create_account.sh john_doe 12345

          # Check if the account is created in accounts.txt with the correct default balance
          grep "Username: john_doe | Account: 12345 | Balance: 1000" accounts.txt || (echo "Account creation failed!" && exit 1)

      # Final Output Verification
      - name: Verify Output Files
        run: |
          # Verify that transaction_log.txt and accounts.txt are not empty after running tests
          [ -s transaction_log.txt ] || (echo "transaction_log.txt is empty!" && exit 1)
          [ -s accounts.txt ] || (echo "accounts.txt is empty!" && exit 1)
